/*
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.ui;

import com.google.inject.Injector;
import course.scheduler.ui.internal.SchedulerActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CourseSchedulerExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SchedulerActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SchedulerActivator activator = SchedulerActivator.getInstance();
		return activator != null ? activator.getInjector(SchedulerActivator.ORG_ADITI_COURSE_SCHEDULER_COURSESCHEDULER) : null;
	}

}
