/*
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CourseSchedulerGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class CourseSchedulerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.aditi.course.scheduler.CourseScheduler.CourseScheduler");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsElementParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//CourseScheduler:
		//    elements+=Element*;
		@Override public ParserRule getRule() { return rule; }
		
		//elements+=Element*
		public Assignment getElementsAssignment() { return cElementsAssignment; }
		
		//Element
		public RuleCall getElementsElementParserRuleCall_0() { return cElementsElementParserRuleCall_0; }
	}
	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.aditi.course.scheduler.CourseScheduler.Element");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCourseParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRoomParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTimeSlotParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cScheduleTriggerParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Element:
		//    Course | Room | TimeSlot | ScheduleTrigger;
		@Override public ParserRule getRule() { return rule; }
		
		//Course | Room | TimeSlot | ScheduleTrigger
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Course
		public RuleCall getCourseParserRuleCall_0() { return cCourseParserRuleCall_0; }
		
		//Room
		public RuleCall getRoomParserRuleCall_1() { return cRoomParserRuleCall_1; }
		
		//TimeSlot
		public RuleCall getTimeSlotParserRuleCall_2() { return cTimeSlotParserRuleCall_2; }
		
		//ScheduleTrigger
		public RuleCall getScheduleTriggerParserRuleCall_3() { return cScheduleTriggerParserRuleCall_3; }
	}
	public class CourseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.aditi.course.scheduler.CourseScheduler.Course");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCourseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cTeacherKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTeacherNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTeacherNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cTeacherNameAssignment_3.eContents().get(0);
		private final Keyword cTeacher_idKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTeacherIdAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTeacherIdSTRINGTerminalRuleCall_5_0 = (RuleCall)cTeacherIdAssignment_5.eContents().get(0);
		private final Keyword cDurationKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cDurationAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cDurationINTTerminalRuleCall_7_0 = (RuleCall)cDurationAssignment_7.eContents().get(0);
		private final Keyword cHKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cSessionsKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cSessionsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cSessionsINTTerminalRuleCall_10_0 = (RuleCall)cSessionsAssignment_10.eContents().get(0);
		private final Keyword cStudent_countKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cStudentCountAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cStudentCountINTTerminalRuleCall_12_0 = (RuleCall)cStudentCountAssignment_12.eContents().get(0);
		private final Keyword cDayKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cDayAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cDayDayEnumRuleCall_14_0 = (RuleCall)cDayAssignment_14.eContents().get(0);
		private final Keyword cBatchesKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cLeftSquareBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cBatchesAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cBatchesSTRINGTerminalRuleCall_17_0 = (RuleCall)cBatchesAssignment_17.eContents().get(0);
		private final Group cGroup_18 = (Group)cGroup.eContents().get(18);
		private final Keyword cCommaKeyword_18_0 = (Keyword)cGroup_18.eContents().get(0);
		private final Assignment cBatchesAssignment_18_1 = (Assignment)cGroup_18.eContents().get(1);
		private final RuleCall cBatchesSTRINGTerminalRuleCall_18_1_0 = (RuleCall)cBatchesAssignment_18_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Keyword cPrefersKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Keyword cLeftSquareBracketKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Assignment cPrefersAssignment_22 = (Assignment)cGroup.eContents().get(22);
		private final RuleCall cPrefersDayEnumRuleCall_22_0 = (RuleCall)cPrefersAssignment_22.eContents().get(0);
		private final Group cGroup_23 = (Group)cGroup.eContents().get(23);
		private final Keyword cCommaKeyword_23_0 = (Keyword)cGroup_23.eContents().get(0);
		private final Assignment cPrefersAssignment_23_1 = (Assignment)cGroup_23.eContents().get(1);
		private final RuleCall cPrefersDayEnumRuleCall_23_1_0 = (RuleCall)cPrefersAssignment_23_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_24 = (Keyword)cGroup.eContents().get(24);
		private final Keyword cPreferred_sessionsKeyword_25 = (Keyword)cGroup.eContents().get(25);
		private final Keyword cLeftSquareBracketKeyword_26 = (Keyword)cGroup.eContents().get(26);
		private final Assignment cPreferredSessionsAssignment_27 = (Assignment)cGroup.eContents().get(27);
		private final RuleCall cPreferredSessionsINTTerminalRuleCall_27_0 = (RuleCall)cPreferredSessionsAssignment_27.eContents().get(0);
		private final Group cGroup_28 = (Group)cGroup.eContents().get(28);
		private final Keyword cCommaKeyword_28_0 = (Keyword)cGroup_28.eContents().get(0);
		private final Assignment cPreferredSessionsAssignment_28_1 = (Assignment)cGroup_28.eContents().get(1);
		private final RuleCall cPreferredSessionsINTTerminalRuleCall_28_1_0 = (RuleCall)cPreferredSessionsAssignment_28_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_29 = (Keyword)cGroup.eContents().get(29);
		
		//Course:
		//    'course' name=STRING
		//    'teacher' teacherName=STRING
		//    'teacher_id' teacherId=STRING
		//    'duration' duration=INT 'h'
		//    'sessions' sessions=INT
		//    'student_count' studentCount=INT
		//    'day' day=Day
		//    'batches' '[' batches+=STRING (',' batches+=STRING)* ']'
		//    'prefers' '[' prefers+=Day (',' prefers+=Day)* ']'
		//    'preferred_sessions' '[' preferredSessions+=INT (',' preferredSessions+=INT)* ']'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'course' name=STRING
		//'teacher' teacherName=STRING
		//'teacher_id' teacherId=STRING
		//'duration' duration=INT 'h'
		//'sessions' sessions=INT
		//'student_count' studentCount=INT
		//'day' day=Day
		//'batches' '[' batches+=STRING (',' batches+=STRING)* ']'
		//'prefers' '[' prefers+=Day (',' prefers+=Day)* ']'
		//'preferred_sessions' '[' preferredSessions+=INT (',' preferredSessions+=INT)* ']'
		public Group getGroup() { return cGroup; }
		
		//'course'
		public Keyword getCourseKeyword_0() { return cCourseKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'teacher'
		public Keyword getTeacherKeyword_2() { return cTeacherKeyword_2; }
		
		//teacherName=STRING
		public Assignment getTeacherNameAssignment_3() { return cTeacherNameAssignment_3; }
		
		//STRING
		public RuleCall getTeacherNameSTRINGTerminalRuleCall_3_0() { return cTeacherNameSTRINGTerminalRuleCall_3_0; }
		
		//'teacher_id'
		public Keyword getTeacher_idKeyword_4() { return cTeacher_idKeyword_4; }
		
		//teacherId=STRING
		public Assignment getTeacherIdAssignment_5() { return cTeacherIdAssignment_5; }
		
		//STRING
		public RuleCall getTeacherIdSTRINGTerminalRuleCall_5_0() { return cTeacherIdSTRINGTerminalRuleCall_5_0; }
		
		//'duration'
		public Keyword getDurationKeyword_6() { return cDurationKeyword_6; }
		
		//duration=INT
		public Assignment getDurationAssignment_7() { return cDurationAssignment_7; }
		
		//INT
		public RuleCall getDurationINTTerminalRuleCall_7_0() { return cDurationINTTerminalRuleCall_7_0; }
		
		//'h'
		public Keyword getHKeyword_8() { return cHKeyword_8; }
		
		//'sessions'
		public Keyword getSessionsKeyword_9() { return cSessionsKeyword_9; }
		
		//sessions=INT
		public Assignment getSessionsAssignment_10() { return cSessionsAssignment_10; }
		
		//INT
		public RuleCall getSessionsINTTerminalRuleCall_10_0() { return cSessionsINTTerminalRuleCall_10_0; }
		
		//'student_count'
		public Keyword getStudent_countKeyword_11() { return cStudent_countKeyword_11; }
		
		//studentCount=INT
		public Assignment getStudentCountAssignment_12() { return cStudentCountAssignment_12; }
		
		//INT
		public RuleCall getStudentCountINTTerminalRuleCall_12_0() { return cStudentCountINTTerminalRuleCall_12_0; }
		
		//'day'
		public Keyword getDayKeyword_13() { return cDayKeyword_13; }
		
		//day=Day
		public Assignment getDayAssignment_14() { return cDayAssignment_14; }
		
		//Day
		public RuleCall getDayDayEnumRuleCall_14_0() { return cDayDayEnumRuleCall_14_0; }
		
		//'batches'
		public Keyword getBatchesKeyword_15() { return cBatchesKeyword_15; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_16() { return cLeftSquareBracketKeyword_16; }
		
		//batches+=STRING
		public Assignment getBatchesAssignment_17() { return cBatchesAssignment_17; }
		
		//STRING
		public RuleCall getBatchesSTRINGTerminalRuleCall_17_0() { return cBatchesSTRINGTerminalRuleCall_17_0; }
		
		//(',' batches+=STRING)*
		public Group getGroup_18() { return cGroup_18; }
		
		//','
		public Keyword getCommaKeyword_18_0() { return cCommaKeyword_18_0; }
		
		//batches+=STRING
		public Assignment getBatchesAssignment_18_1() { return cBatchesAssignment_18_1; }
		
		//STRING
		public RuleCall getBatchesSTRINGTerminalRuleCall_18_1_0() { return cBatchesSTRINGTerminalRuleCall_18_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_19() { return cRightSquareBracketKeyword_19; }
		
		//'prefers'
		public Keyword getPrefersKeyword_20() { return cPrefersKeyword_20; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_21() { return cLeftSquareBracketKeyword_21; }
		
		//prefers+=Day
		public Assignment getPrefersAssignment_22() { return cPrefersAssignment_22; }
		
		//Day
		public RuleCall getPrefersDayEnumRuleCall_22_0() { return cPrefersDayEnumRuleCall_22_0; }
		
		//(',' prefers+=Day)*
		public Group getGroup_23() { return cGroup_23; }
		
		//','
		public Keyword getCommaKeyword_23_0() { return cCommaKeyword_23_0; }
		
		//prefers+=Day
		public Assignment getPrefersAssignment_23_1() { return cPrefersAssignment_23_1; }
		
		//Day
		public RuleCall getPrefersDayEnumRuleCall_23_1_0() { return cPrefersDayEnumRuleCall_23_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_24() { return cRightSquareBracketKeyword_24; }
		
		//'preferred_sessions'
		public Keyword getPreferred_sessionsKeyword_25() { return cPreferred_sessionsKeyword_25; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_26() { return cLeftSquareBracketKeyword_26; }
		
		//preferredSessions+=INT
		public Assignment getPreferredSessionsAssignment_27() { return cPreferredSessionsAssignment_27; }
		
		//INT
		public RuleCall getPreferredSessionsINTTerminalRuleCall_27_0() { return cPreferredSessionsINTTerminalRuleCall_27_0; }
		
		//(',' preferredSessions+=INT)*
		public Group getGroup_28() { return cGroup_28; }
		
		//','
		public Keyword getCommaKeyword_28_0() { return cCommaKeyword_28_0; }
		
		//preferredSessions+=INT
		public Assignment getPreferredSessionsAssignment_28_1() { return cPreferredSessionsAssignment_28_1; }
		
		//INT
		public RuleCall getPreferredSessionsINTTerminalRuleCall_28_1_0() { return cPreferredSessionsINTTerminalRuleCall_28_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_29() { return cRightSquareBracketKeyword_29; }
	}
	public class RoomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.aditi.course.scheduler.CourseScheduler.Room");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRoomKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cCapacityKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCapacityAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCapacityINTTerminalRuleCall_3_0 = (RuleCall)cCapacityAssignment_3.eContents().get(0);
		private final Keyword cAvailableKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cAvailabilityAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cAvailabilityAvailabilityParserRuleCall_6_0 = (RuleCall)cAvailabilityAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cAvailabilityAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cAvailabilityAvailabilityParserRuleCall_7_1_0 = (RuleCall)cAvailabilityAssignment_7_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Room:
		//    'room' name=STRING
		//    'capacity' capacity=INT
		//    'available' '[' availability+=Availability (',' availability+=Availability)* ']';
		@Override public ParserRule getRule() { return rule; }
		
		//'room' name=STRING
		//'capacity' capacity=INT
		//'available' '[' availability+=Availability (',' availability+=Availability)* ']'
		public Group getGroup() { return cGroup; }
		
		//'room'
		public Keyword getRoomKeyword_0() { return cRoomKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'capacity'
		public Keyword getCapacityKeyword_2() { return cCapacityKeyword_2; }
		
		//capacity=INT
		public Assignment getCapacityAssignment_3() { return cCapacityAssignment_3; }
		
		//INT
		public RuleCall getCapacityINTTerminalRuleCall_3_0() { return cCapacityINTTerminalRuleCall_3_0; }
		
		//'available'
		public Keyword getAvailableKeyword_4() { return cAvailableKeyword_4; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5() { return cLeftSquareBracketKeyword_5; }
		
		//availability+=Availability
		public Assignment getAvailabilityAssignment_6() { return cAvailabilityAssignment_6; }
		
		//Availability
		public RuleCall getAvailabilityAvailabilityParserRuleCall_6_0() { return cAvailabilityAvailabilityParserRuleCall_6_0; }
		
		//(',' availability+=Availability)*
		public Group getGroup_7() { return cGroup_7; }
		
		//','
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//availability+=Availability
		public Assignment getAvailabilityAssignment_7_1() { return cAvailabilityAssignment_7_1; }
		
		//Availability
		public RuleCall getAvailabilityAvailabilityParserRuleCall_7_1_0() { return cAvailabilityAvailabilityParserRuleCall_7_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_8() { return cRightSquareBracketKeyword_8; }
	}
	public class AvailabilityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.aditi.course.scheduler.CourseScheduler.Availability");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDayAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDayDayEnumRuleCall_0_0 = (RuleCall)cDayAssignment_0.eContents().get(0);
		private final Assignment cStartAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStartTIMETerminalRuleCall_1_0 = (RuleCall)cStartAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEndAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEndTIMETerminalRuleCall_3_0 = (RuleCall)cEndAssignment_3.eContents().get(0);
		
		//Availability:
		//    day=Day start=TIME '-' end=TIME;
		@Override public ParserRule getRule() { return rule; }
		
		//day=Day start=TIME '-' end=TIME
		public Group getGroup() { return cGroup; }
		
		//day=Day
		public Assignment getDayAssignment_0() { return cDayAssignment_0; }
		
		//Day
		public RuleCall getDayDayEnumRuleCall_0_0() { return cDayDayEnumRuleCall_0_0; }
		
		//start=TIME
		public Assignment getStartAssignment_1() { return cStartAssignment_1; }
		
		//TIME
		public RuleCall getStartTIMETerminalRuleCall_1_0() { return cStartTIMETerminalRuleCall_1_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_2() { return cHyphenMinusKeyword_2; }
		
		//end=TIME
		public Assignment getEndAssignment_3() { return cEndAssignment_3; }
		
		//TIME
		public RuleCall getEndTIMETerminalRuleCall_3_0() { return cEndTIMETerminalRuleCall_3_0; }
	}
	public class TimeSlotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.aditi.course.scheduler.CourseScheduler.TimeSlot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTime_slotKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cStartAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStartTIMETerminalRuleCall_2_0 = (RuleCall)cStartAssignment_2.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cEndAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEndTIMETerminalRuleCall_4_0 = (RuleCall)cEndAssignment_4.eContents().get(0);
		
		//TimeSlot:
		//    'time_slot' name=STRING start=TIME '-' end=TIME;
		@Override public ParserRule getRule() { return rule; }
		
		//'time_slot' name=STRING start=TIME '-' end=TIME
		public Group getGroup() { return cGroup; }
		
		//'time_slot'
		public Keyword getTime_slotKeyword_0() { return cTime_slotKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//start=TIME
		public Assignment getStartAssignment_2() { return cStartAssignment_2; }
		
		//TIME
		public RuleCall getStartTIMETerminalRuleCall_2_0() { return cStartTIMETerminalRuleCall_2_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_3() { return cHyphenMinusKeyword_3; }
		
		//end=TIME
		public Assignment getEndAssignment_4() { return cEndAssignment_4; }
		
		//TIME
		public RuleCall getEndTIMETerminalRuleCall_4_0() { return cEndTIMETerminalRuleCall_4_0; }
	}
	public class ScheduleTriggerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.aditi.course.scheduler.CourseScheduler.ScheduleTrigger");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cScheduleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cAutoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//ScheduleTrigger:
		//    'schedule' 'auto';
		@Override public ParserRule getRule() { return rule; }
		
		//'schedule' 'auto'
		public Group getGroup() { return cGroup; }
		
		//'schedule'
		public Keyword getScheduleKeyword_0() { return cScheduleKeyword_0; }
		
		//'auto'
		public Keyword getAutoKeyword_1() { return cAutoKeyword_1; }
	}
	
	public class DayElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.aditi.course.scheduler.CourseScheduler.Day");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMonEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMonMonKeyword_0_0 = (Keyword)cMonEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cTueEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cTueTueKeyword_1_0 = (Keyword)cTueEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cWedEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cWedWedKeyword_2_0 = (Keyword)cWedEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cThuEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cThuThuKeyword_3_0 = (Keyword)cThuEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cFriEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cFriFriKeyword_4_0 = (Keyword)cFriEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cSatEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cSatSatKeyword_5_0 = (Keyword)cSatEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cSunEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cSunSunKeyword_6_0 = (Keyword)cSunEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum Day:
		//    Mon | Tue | Wed | Thu | Fri | Sat | Sun;
		public EnumRule getRule() { return rule; }
		
		//Mon | Tue | Wed | Thu | Fri | Sat | Sun
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Mon
		public EnumLiteralDeclaration getMonEnumLiteralDeclaration_0() { return cMonEnumLiteralDeclaration_0; }
		
		public Keyword getMonMonKeyword_0_0() { return cMonMonKeyword_0_0; }
		
		//Tue
		public EnumLiteralDeclaration getTueEnumLiteralDeclaration_1() { return cTueEnumLiteralDeclaration_1; }
		
		public Keyword getTueTueKeyword_1_0() { return cTueTueKeyword_1_0; }
		
		//Wed
		public EnumLiteralDeclaration getWedEnumLiteralDeclaration_2() { return cWedEnumLiteralDeclaration_2; }
		
		public Keyword getWedWedKeyword_2_0() { return cWedWedKeyword_2_0; }
		
		//Thu
		public EnumLiteralDeclaration getThuEnumLiteralDeclaration_3() { return cThuEnumLiteralDeclaration_3; }
		
		public Keyword getThuThuKeyword_3_0() { return cThuThuKeyword_3_0; }
		
		//Fri
		public EnumLiteralDeclaration getFriEnumLiteralDeclaration_4() { return cFriEnumLiteralDeclaration_4; }
		
		public Keyword getFriFriKeyword_4_0() { return cFriFriKeyword_4_0; }
		
		//Sat
		public EnumLiteralDeclaration getSatEnumLiteralDeclaration_5() { return cSatEnumLiteralDeclaration_5; }
		
		public Keyword getSatSatKeyword_5_0() { return cSatSatKeyword_5_0; }
		
		//Sun
		public EnumLiteralDeclaration getSunEnumLiteralDeclaration_6() { return cSunEnumLiteralDeclaration_6; }
		
		public Keyword getSunSunKeyword_6_0() { return cSunSunKeyword_6_0; }
	}
	
	private final CourseSchedulerElements pCourseScheduler;
	private final ElementElements pElement;
	private final CourseElements pCourse;
	private final RoomElements pRoom;
	private final AvailabilityElements pAvailability;
	private final TimeSlotElements pTimeSlot;
	private final ScheduleTriggerElements pScheduleTrigger;
	private final DayElements eDay;
	private final TerminalRule tTIME;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CourseSchedulerGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pCourseScheduler = new CourseSchedulerElements();
		this.pElement = new ElementElements();
		this.pCourse = new CourseElements();
		this.pRoom = new RoomElements();
		this.pAvailability = new AvailabilityElements();
		this.pTimeSlot = new TimeSlotElements();
		this.pScheduleTrigger = new ScheduleTriggerElements();
		this.eDay = new DayElements();
		this.tTIME = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.aditi.course.scheduler.CourseScheduler.TIME");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.aditi.course.scheduler.CourseScheduler".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//CourseScheduler:
	//    elements+=Element*;
	public CourseSchedulerElements getCourseSchedulerAccess() {
		return pCourseScheduler;
	}
	
	public ParserRule getCourseSchedulerRule() {
		return getCourseSchedulerAccess().getRule();
	}
	
	//Element:
	//    Course | Room | TimeSlot | ScheduleTrigger;
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}
	
	//Course:
	//    'course' name=STRING
	//    'teacher' teacherName=STRING
	//    'teacher_id' teacherId=STRING
	//    'duration' duration=INT 'h'
	//    'sessions' sessions=INT
	//    'student_count' studentCount=INT
	//    'day' day=Day
	//    'batches' '[' batches+=STRING (',' batches+=STRING)* ']'
	//    'prefers' '[' prefers+=Day (',' prefers+=Day)* ']'
	//    'preferred_sessions' '[' preferredSessions+=INT (',' preferredSessions+=INT)* ']'
	//;
	public CourseElements getCourseAccess() {
		return pCourse;
	}
	
	public ParserRule getCourseRule() {
		return getCourseAccess().getRule();
	}
	
	//Room:
	//    'room' name=STRING
	//    'capacity' capacity=INT
	//    'available' '[' availability+=Availability (',' availability+=Availability)* ']';
	public RoomElements getRoomAccess() {
		return pRoom;
	}
	
	public ParserRule getRoomRule() {
		return getRoomAccess().getRule();
	}
	
	//Availability:
	//    day=Day start=TIME '-' end=TIME;
	public AvailabilityElements getAvailabilityAccess() {
		return pAvailability;
	}
	
	public ParserRule getAvailabilityRule() {
		return getAvailabilityAccess().getRule();
	}
	
	//TimeSlot:
	//    'time_slot' name=STRING start=TIME '-' end=TIME;
	public TimeSlotElements getTimeSlotAccess() {
		return pTimeSlot;
	}
	
	public ParserRule getTimeSlotRule() {
		return getTimeSlotAccess().getRule();
	}
	
	//ScheduleTrigger:
	//    'schedule' 'auto';
	public ScheduleTriggerElements getScheduleTriggerAccess() {
		return pScheduleTrigger;
	}
	
	public ParserRule getScheduleTriggerRule() {
		return getScheduleTriggerAccess().getRule();
	}
	
	//enum Day:
	//    Mon | Tue | Wed | Thu | Fri | Sat | Sun;
	public DayElements getDayAccess() {
		return eDay;
	}
	
	public EnumRule getDayRule() {
		return getDayAccess().getRule();
	}
	
	//terminal TIME: ('0'..'2') ('0'..'9') ':' ('0'..'5') ('0'..'9');
	public TerminalRule getTIMERule() {
		return tTIME;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
