/*
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.aditi.course.scheduler.CourseSchedulerRuntimeModule;
import org.aditi.course.scheduler.CourseSchedulerStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CourseSchedulerIdeSetup extends CourseSchedulerStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CourseSchedulerRuntimeModule(), new CourseSchedulerIdeModule()));
	}
	
}
