/*
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.ide;


/**
 * Use this class to register ide components.
 */
public class CourseSchedulerIdeModule extends AbstractCourseSchedulerIdeModule {
}
