/*
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CourseSchedulerUiModule extends AbstractCourseSchedulerUiModule {

	public CourseSchedulerUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
