/**
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.courseScheduler;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Availability</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.Availability#getDay <em>Day</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.Availability#getStart <em>Start</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.Availability#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getAvailability()
 * @model
 * @generated
 */
public interface Availability extends EObject
{
  /**
   * Returns the value of the '<em><b>Day</b></em>' attribute.
   * The literals are from the enumeration {@link org.aditi.course.scheduler.courseScheduler.Day}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Day</em>' attribute.
   * @see org.aditi.course.scheduler.courseScheduler.Day
   * @see #setDay(Day)
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getAvailability_Day()
   * @model
   * @generated
   */
  Day getDay();

  /**
   * Sets the value of the '{@link org.aditi.course.scheduler.courseScheduler.Availability#getDay <em>Day</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Day</em>' attribute.
   * @see org.aditi.course.scheduler.courseScheduler.Day
   * @see #getDay()
   * @generated
   */
  void setDay(Day value);

  /**
   * Returns the value of the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' attribute.
   * @see #setStart(String)
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getAvailability_Start()
   * @model
   * @generated
   */
  String getStart();

  /**
   * Sets the value of the '{@link org.aditi.course.scheduler.courseScheduler.Availability#getStart <em>Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' attribute.
   * @see #getStart()
   * @generated
   */
  void setStart(String value);

  /**
   * Returns the value of the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' attribute.
   * @see #setEnd(String)
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getAvailability_End()
   * @model
   * @generated
   */
  String getEnd();

  /**
   * Sets the value of the '{@link org.aditi.course.scheduler.courseScheduler.Availability#getEnd <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' attribute.
   * @see #getEnd()
   * @generated
   */
  void setEnd(String value);

} // Availability
