/**
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.courseScheduler;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage
 * @generated
 */
public interface CourseSchedulerFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CourseSchedulerFactory eINSTANCE = org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Course Scheduler</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Course Scheduler</em>'.
   * @generated
   */
  CourseScheduler createCourseScheduler();

  /**
   * Returns a new object of class '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element</em>'.
   * @generated
   */
  Element createElement();

  /**
   * Returns a new object of class '<em>Course</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Course</em>'.
   * @generated
   */
  Course createCourse();

  /**
   * Returns a new object of class '<em>Room</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Room</em>'.
   * @generated
   */
  Room createRoom();

  /**
   * Returns a new object of class '<em>Availability</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Availability</em>'.
   * @generated
   */
  Availability createAvailability();

  /**
   * Returns a new object of class '<em>Time Slot</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Time Slot</em>'.
   * @generated
   */
  TimeSlot createTimeSlot();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CourseSchedulerPackage getCourseSchedulerPackage();

} //CourseSchedulerFactory
