/**
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.courseScheduler;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Course Scheduler</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.CourseScheduler#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getCourseScheduler()
 * @model
 * @generated
 */
public interface CourseScheduler extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.aditi.course.scheduler.courseScheduler.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getCourseScheduler_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElements();

} // CourseScheduler
