/**
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.courseScheduler;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Course</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.Course#getTeacherName <em>Teacher Name</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.Course#getTeacherId <em>Teacher Id</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.Course#getDuration <em>Duration</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.Course#getSessions <em>Sessions</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.Course#getStudentCount <em>Student Count</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.Course#getDay <em>Day</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.Course#getBatches <em>Batches</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.Course#getPrefers <em>Prefers</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.Course#getPreferredSessions <em>Preferred Sessions</em>}</li>
 * </ul>
 *
 * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getCourse()
 * @model
 * @generated
 */
public interface Course extends Element
{
  /**
   * Returns the value of the '<em><b>Teacher Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Teacher Name</em>' attribute.
   * @see #setTeacherName(String)
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getCourse_TeacherName()
   * @model
   * @generated
   */
  String getTeacherName();

  /**
   * Sets the value of the '{@link org.aditi.course.scheduler.courseScheduler.Course#getTeacherName <em>Teacher Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Teacher Name</em>' attribute.
   * @see #getTeacherName()
   * @generated
   */
  void setTeacherName(String value);

  /**
   * Returns the value of the '<em><b>Teacher Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Teacher Id</em>' attribute.
   * @see #setTeacherId(String)
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getCourse_TeacherId()
   * @model
   * @generated
   */
  String getTeacherId();

  /**
   * Sets the value of the '{@link org.aditi.course.scheduler.courseScheduler.Course#getTeacherId <em>Teacher Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Teacher Id</em>' attribute.
   * @see #getTeacherId()
   * @generated
   */
  void setTeacherId(String value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(int)
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getCourse_Duration()
   * @model
   * @generated
   */
  int getDuration();

  /**
   * Sets the value of the '{@link org.aditi.course.scheduler.courseScheduler.Course#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(int value);

  /**
   * Returns the value of the '<em><b>Sessions</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sessions</em>' attribute.
   * @see #setSessions(int)
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getCourse_Sessions()
   * @model
   * @generated
   */
  int getSessions();

  /**
   * Sets the value of the '{@link org.aditi.course.scheduler.courseScheduler.Course#getSessions <em>Sessions</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sessions</em>' attribute.
   * @see #getSessions()
   * @generated
   */
  void setSessions(int value);

  /**
   * Returns the value of the '<em><b>Student Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Student Count</em>' attribute.
   * @see #setStudentCount(int)
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getCourse_StudentCount()
   * @model
   * @generated
   */
  int getStudentCount();

  /**
   * Sets the value of the '{@link org.aditi.course.scheduler.courseScheduler.Course#getStudentCount <em>Student Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Student Count</em>' attribute.
   * @see #getStudentCount()
   * @generated
   */
  void setStudentCount(int value);

  /**
   * Returns the value of the '<em><b>Day</b></em>' attribute.
   * The literals are from the enumeration {@link org.aditi.course.scheduler.courseScheduler.Day}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Day</em>' attribute.
   * @see org.aditi.course.scheduler.courseScheduler.Day
   * @see #setDay(Day)
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getCourse_Day()
   * @model
   * @generated
   */
  Day getDay();

  /**
   * Sets the value of the '{@link org.aditi.course.scheduler.courseScheduler.Course#getDay <em>Day</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Day</em>' attribute.
   * @see org.aditi.course.scheduler.courseScheduler.Day
   * @see #getDay()
   * @generated
   */
  void setDay(Day value);

  /**
   * Returns the value of the '<em><b>Batches</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Batches</em>' attribute list.
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getCourse_Batches()
   * @model unique="false"
   * @generated
   */
  EList<String> getBatches();

  /**
   * Returns the value of the '<em><b>Prefers</b></em>' attribute list.
   * The list contents are of type {@link org.aditi.course.scheduler.courseScheduler.Day}.
   * The literals are from the enumeration {@link org.aditi.course.scheduler.courseScheduler.Day}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefers</em>' attribute list.
   * @see org.aditi.course.scheduler.courseScheduler.Day
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getCourse_Prefers()
   * @model unique="false"
   * @generated
   */
  EList<Day> getPrefers();

  /**
   * Returns the value of the '<em><b>Preferred Sessions</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preferred Sessions</em>' attribute list.
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getCourse_PreferredSessions()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getPreferredSessions();

} // Course
