/**
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.courseScheduler;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerFactory
 * @model kind="package"
 * @generated
 */
public interface CourseSchedulerPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "courseScheduler";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.aditi.org/course/scheduler";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "courseScheduler";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CourseSchedulerPackage eINSTANCE = org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl.init();

  /**
   * The meta object id for the '{@link org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerImpl <em>Course Scheduler</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerImpl
   * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl#getCourseScheduler()
   * @generated
   */
  int COURSE_SCHEDULER = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE_SCHEDULER__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Course Scheduler</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE_SCHEDULER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.aditi.course.scheduler.courseScheduler.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.aditi.course.scheduler.courseScheduler.impl.ElementImpl
   * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.aditi.course.scheduler.courseScheduler.impl.CourseImpl <em>Course</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.aditi.course.scheduler.courseScheduler.impl.CourseImpl
   * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl#getCourse()
   * @generated
   */
  int COURSE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Teacher Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__TEACHER_NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Teacher Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__TEACHER_ID = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__DURATION = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Sessions</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__SESSIONS = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Student Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__STUDENT_COUNT = ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Day</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__DAY = ELEMENT_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Batches</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__BATCHES = ELEMENT_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Prefers</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__PREFERS = ELEMENT_FEATURE_COUNT + 7;

  /**
   * The feature id for the '<em><b>Preferred Sessions</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__PREFERRED_SESSIONS = ELEMENT_FEATURE_COUNT + 8;

  /**
   * The number of structural features of the '<em>Course</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 9;

  /**
   * The meta object id for the '{@link org.aditi.course.scheduler.courseScheduler.impl.RoomImpl <em>Room</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.aditi.course.scheduler.courseScheduler.impl.RoomImpl
   * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl#getRoom()
   * @generated
   */
  int ROOM = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__CAPACITY = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Availability</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__AVAILABILITY = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Room</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.aditi.course.scheduler.courseScheduler.impl.AvailabilityImpl <em>Availability</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.aditi.course.scheduler.courseScheduler.impl.AvailabilityImpl
   * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl#getAvailability()
   * @generated
   */
  int AVAILABILITY = 4;

  /**
   * The feature id for the '<em><b>Day</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVAILABILITY__DAY = 0;

  /**
   * The feature id for the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVAILABILITY__START = 1;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVAILABILITY__END = 2;

  /**
   * The number of structural features of the '<em>Availability</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVAILABILITY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.aditi.course.scheduler.courseScheduler.impl.TimeSlotImpl <em>Time Slot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.aditi.course.scheduler.courseScheduler.impl.TimeSlotImpl
   * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl#getTimeSlot()
   * @generated
   */
  int TIME_SLOT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_SLOT__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_SLOT__START = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_SLOT__END = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Time Slot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_SLOT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.aditi.course.scheduler.courseScheduler.Day <em>Day</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.aditi.course.scheduler.courseScheduler.Day
   * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl#getDay()
   * @generated
   */
  int DAY = 6;


  /**
   * Returns the meta object for class '{@link org.aditi.course.scheduler.courseScheduler.CourseScheduler <em>Course Scheduler</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Course Scheduler</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.CourseScheduler
   * @generated
   */
  EClass getCourseScheduler();

  /**
   * Returns the meta object for the containment reference list '{@link org.aditi.course.scheduler.courseScheduler.CourseScheduler#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.CourseScheduler#getElements()
   * @see #getCourseScheduler()
   * @generated
   */
  EReference getCourseScheduler_Elements();

  /**
   * Returns the meta object for class '{@link org.aditi.course.scheduler.courseScheduler.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.aditi.course.scheduler.courseScheduler.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for class '{@link org.aditi.course.scheduler.courseScheduler.Course <em>Course</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Course</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Course
   * @generated
   */
  EClass getCourse();

  /**
   * Returns the meta object for the attribute '{@link org.aditi.course.scheduler.courseScheduler.Course#getTeacherName <em>Teacher Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Teacher Name</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Course#getTeacherName()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_TeacherName();

  /**
   * Returns the meta object for the attribute '{@link org.aditi.course.scheduler.courseScheduler.Course#getTeacherId <em>Teacher Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Teacher Id</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Course#getTeacherId()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_TeacherId();

  /**
   * Returns the meta object for the attribute '{@link org.aditi.course.scheduler.courseScheduler.Course#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Course#getDuration()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Duration();

  /**
   * Returns the meta object for the attribute '{@link org.aditi.course.scheduler.courseScheduler.Course#getSessions <em>Sessions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sessions</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Course#getSessions()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Sessions();

  /**
   * Returns the meta object for the attribute '{@link org.aditi.course.scheduler.courseScheduler.Course#getStudentCount <em>Student Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Student Count</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Course#getStudentCount()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_StudentCount();

  /**
   * Returns the meta object for the attribute '{@link org.aditi.course.scheduler.courseScheduler.Course#getDay <em>Day</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Day</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Course#getDay()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Day();

  /**
   * Returns the meta object for the attribute list '{@link org.aditi.course.scheduler.courseScheduler.Course#getBatches <em>Batches</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Batches</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Course#getBatches()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Batches();

  /**
   * Returns the meta object for the attribute list '{@link org.aditi.course.scheduler.courseScheduler.Course#getPrefers <em>Prefers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Prefers</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Course#getPrefers()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Prefers();

  /**
   * Returns the meta object for the attribute list '{@link org.aditi.course.scheduler.courseScheduler.Course#getPreferredSessions <em>Preferred Sessions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Preferred Sessions</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Course#getPreferredSessions()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_PreferredSessions();

  /**
   * Returns the meta object for class '{@link org.aditi.course.scheduler.courseScheduler.Room <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Room
   * @generated
   */
  EClass getRoom();

  /**
   * Returns the meta object for the attribute '{@link org.aditi.course.scheduler.courseScheduler.Room#getCapacity <em>Capacity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Capacity</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Room#getCapacity()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Capacity();

  /**
   * Returns the meta object for the containment reference list '{@link org.aditi.course.scheduler.courseScheduler.Room#getAvailability <em>Availability</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Availability</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Room#getAvailability()
   * @see #getRoom()
   * @generated
   */
  EReference getRoom_Availability();

  /**
   * Returns the meta object for class '{@link org.aditi.course.scheduler.courseScheduler.Availability <em>Availability</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Availability</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Availability
   * @generated
   */
  EClass getAvailability();

  /**
   * Returns the meta object for the attribute '{@link org.aditi.course.scheduler.courseScheduler.Availability#getDay <em>Day</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Day</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Availability#getDay()
   * @see #getAvailability()
   * @generated
   */
  EAttribute getAvailability_Day();

  /**
   * Returns the meta object for the attribute '{@link org.aditi.course.scheduler.courseScheduler.Availability#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Availability#getStart()
   * @see #getAvailability()
   * @generated
   */
  EAttribute getAvailability_Start();

  /**
   * Returns the meta object for the attribute '{@link org.aditi.course.scheduler.courseScheduler.Availability#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Availability#getEnd()
   * @see #getAvailability()
   * @generated
   */
  EAttribute getAvailability_End();

  /**
   * Returns the meta object for class '{@link org.aditi.course.scheduler.courseScheduler.TimeSlot <em>Time Slot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time Slot</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.TimeSlot
   * @generated
   */
  EClass getTimeSlot();

  /**
   * Returns the meta object for the attribute '{@link org.aditi.course.scheduler.courseScheduler.TimeSlot#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.TimeSlot#getStart()
   * @see #getTimeSlot()
   * @generated
   */
  EAttribute getTimeSlot_Start();

  /**
   * Returns the meta object for the attribute '{@link org.aditi.course.scheduler.courseScheduler.TimeSlot#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.TimeSlot#getEnd()
   * @see #getTimeSlot()
   * @generated
   */
  EAttribute getTimeSlot_End();

  /**
   * Returns the meta object for enum '{@link org.aditi.course.scheduler.courseScheduler.Day <em>Day</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Day</em>'.
   * @see org.aditi.course.scheduler.courseScheduler.Day
   * @generated
   */
  EEnum getDay();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CourseSchedulerFactory getCourseSchedulerFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerImpl <em>Course Scheduler</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerImpl
     * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl#getCourseScheduler()
     * @generated
     */
    EClass COURSE_SCHEDULER = eINSTANCE.getCourseScheduler();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COURSE_SCHEDULER__ELEMENTS = eINSTANCE.getCourseScheduler_Elements();

    /**
     * The meta object literal for the '{@link org.aditi.course.scheduler.courseScheduler.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.aditi.course.scheduler.courseScheduler.impl.ElementImpl
     * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '{@link org.aditi.course.scheduler.courseScheduler.impl.CourseImpl <em>Course</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.aditi.course.scheduler.courseScheduler.impl.CourseImpl
     * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl#getCourse()
     * @generated
     */
    EClass COURSE = eINSTANCE.getCourse();

    /**
     * The meta object literal for the '<em><b>Teacher Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__TEACHER_NAME = eINSTANCE.getCourse_TeacherName();

    /**
     * The meta object literal for the '<em><b>Teacher Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__TEACHER_ID = eINSTANCE.getCourse_TeacherId();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__DURATION = eINSTANCE.getCourse_Duration();

    /**
     * The meta object literal for the '<em><b>Sessions</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__SESSIONS = eINSTANCE.getCourse_Sessions();

    /**
     * The meta object literal for the '<em><b>Student Count</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__STUDENT_COUNT = eINSTANCE.getCourse_StudentCount();

    /**
     * The meta object literal for the '<em><b>Day</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__DAY = eINSTANCE.getCourse_Day();

    /**
     * The meta object literal for the '<em><b>Batches</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__BATCHES = eINSTANCE.getCourse_Batches();

    /**
     * The meta object literal for the '<em><b>Prefers</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__PREFERS = eINSTANCE.getCourse_Prefers();

    /**
     * The meta object literal for the '<em><b>Preferred Sessions</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__PREFERRED_SESSIONS = eINSTANCE.getCourse_PreferredSessions();

    /**
     * The meta object literal for the '{@link org.aditi.course.scheduler.courseScheduler.impl.RoomImpl <em>Room</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.aditi.course.scheduler.courseScheduler.impl.RoomImpl
     * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl#getRoom()
     * @generated
     */
    EClass ROOM = eINSTANCE.getRoom();

    /**
     * The meta object literal for the '<em><b>Capacity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__CAPACITY = eINSTANCE.getRoom_Capacity();

    /**
     * The meta object literal for the '<em><b>Availability</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM__AVAILABILITY = eINSTANCE.getRoom_Availability();

    /**
     * The meta object literal for the '{@link org.aditi.course.scheduler.courseScheduler.impl.AvailabilityImpl <em>Availability</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.aditi.course.scheduler.courseScheduler.impl.AvailabilityImpl
     * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl#getAvailability()
     * @generated
     */
    EClass AVAILABILITY = eINSTANCE.getAvailability();

    /**
     * The meta object literal for the '<em><b>Day</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AVAILABILITY__DAY = eINSTANCE.getAvailability_Day();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AVAILABILITY__START = eINSTANCE.getAvailability_Start();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AVAILABILITY__END = eINSTANCE.getAvailability_End();

    /**
     * The meta object literal for the '{@link org.aditi.course.scheduler.courseScheduler.impl.TimeSlotImpl <em>Time Slot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.aditi.course.scheduler.courseScheduler.impl.TimeSlotImpl
     * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl#getTimeSlot()
     * @generated
     */
    EClass TIME_SLOT = eINSTANCE.getTimeSlot();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_SLOT__START = eINSTANCE.getTimeSlot_Start();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_SLOT__END = eINSTANCE.getTimeSlot_End();

    /**
     * The meta object literal for the '{@link org.aditi.course.scheduler.courseScheduler.Day <em>Day</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.aditi.course.scheduler.courseScheduler.Day
     * @see org.aditi.course.scheduler.courseScheduler.impl.CourseSchedulerPackageImpl#getDay()
     * @generated
     */
    EEnum DAY = eINSTANCE.getDay();

  }

} //CourseSchedulerPackage
