/**
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.courseScheduler;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Room</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.Room#getCapacity <em>Capacity</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.Room#getAvailability <em>Availability</em>}</li>
 * </ul>
 *
 * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getRoom()
 * @model
 * @generated
 */
public interface Room extends Element
{
  /**
   * Returns the value of the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Capacity</em>' attribute.
   * @see #setCapacity(int)
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getRoom_Capacity()
   * @model
   * @generated
   */
  int getCapacity();

  /**
   * Sets the value of the '{@link org.aditi.course.scheduler.courseScheduler.Room#getCapacity <em>Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Capacity</em>' attribute.
   * @see #getCapacity()
   * @generated
   */
  void setCapacity(int value);

  /**
   * Returns the value of the '<em><b>Availability</b></em>' containment reference list.
   * The list contents are of type {@link org.aditi.course.scheduler.courseScheduler.Availability}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Availability</em>' containment reference list.
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getRoom_Availability()
   * @model containment="true"
   * @generated
   */
  EList<Availability> getAvailability();

} // Room
