/**
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.courseScheduler;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Time Slot</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.TimeSlot#getStart <em>Start</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.TimeSlot#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getTimeSlot()
 * @model
 * @generated
 */
public interface TimeSlot extends Element
{
  /**
   * Returns the value of the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' attribute.
   * @see #setStart(String)
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getTimeSlot_Start()
   * @model
   * @generated
   */
  String getStart();

  /**
   * Sets the value of the '{@link org.aditi.course.scheduler.courseScheduler.TimeSlot#getStart <em>Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' attribute.
   * @see #getStart()
   * @generated
   */
  void setStart(String value);

  /**
   * Returns the value of the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' attribute.
   * @see #setEnd(String)
   * @see org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage#getTimeSlot_End()
   * @model
   * @generated
   */
  String getEnd();

  /**
   * Sets the value of the '{@link org.aditi.course.scheduler.courseScheduler.TimeSlot#getEnd <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' attribute.
   * @see #getEnd()
   * @generated
   */
  void setEnd(String value);

} // TimeSlot
