/*
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.parser.antlr;

import com.google.inject.Inject;
import org.aditi.course.scheduler.parser.antlr.internal.InternalCourseSchedulerParser;
import org.aditi.course.scheduler.services.CourseSchedulerGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CourseSchedulerParser extends AbstractAntlrParser {

	@Inject
	private CourseSchedulerGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCourseSchedulerParser createParser(XtextTokenStream stream) {
		return new InternalCourseSchedulerParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "CourseScheduler";
	}

	public CourseSchedulerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CourseSchedulerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
