/*
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CourseSchedulerAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/aditi/course/scheduler/parser/antlr/internal/InternalCourseScheduler.tokens");
	}
}
