/*
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CourseSchedulerStandaloneSetup extends CourseSchedulerStandaloneSetupGenerated {

	public static void doSetup() {
		new CourseSchedulerStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
