/**
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.courseScheduler.impl;

import java.util.Collection;

import org.aditi.course.scheduler.courseScheduler.Course;
import org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage;
import org.aditi.course.scheduler.courseScheduler.Day;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Course</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.impl.CourseImpl#getTeacherName <em>Teacher Name</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.impl.CourseImpl#getTeacherId <em>Teacher Id</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.impl.CourseImpl#getDuration <em>Duration</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.impl.CourseImpl#getSessions <em>Sessions</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.impl.CourseImpl#getStudentCount <em>Student Count</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.impl.CourseImpl#getDay <em>Day</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.impl.CourseImpl#getBatches <em>Batches</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.impl.CourseImpl#getPrefers <em>Prefers</em>}</li>
 *   <li>{@link org.aditi.course.scheduler.courseScheduler.impl.CourseImpl#getPreferredSessions <em>Preferred Sessions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CourseImpl extends ElementImpl implements Course
{
  /**
   * The default value of the '{@link #getTeacherName() <em>Teacher Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTeacherName()
   * @generated
   * @ordered
   */
  protected static final String TEACHER_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTeacherName() <em>Teacher Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTeacherName()
   * @generated
   * @ordered
   */
  protected String teacherName = TEACHER_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getTeacherId() <em>Teacher Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTeacherId()
   * @generated
   * @ordered
   */
  protected static final String TEACHER_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTeacherId() <em>Teacher Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTeacherId()
   * @generated
   * @ordered
   */
  protected String teacherId = TEACHER_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getDuration() <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDuration()
   * @generated
   * @ordered
   */
  protected static final int DURATION_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDuration() <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDuration()
   * @generated
   * @ordered
   */
  protected int duration = DURATION_EDEFAULT;

  /**
   * The default value of the '{@link #getSessions() <em>Sessions</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSessions()
   * @generated
   * @ordered
   */
  protected static final int SESSIONS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSessions() <em>Sessions</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSessions()
   * @generated
   * @ordered
   */
  protected int sessions = SESSIONS_EDEFAULT;

  /**
   * The default value of the '{@link #getStudentCount() <em>Student Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStudentCount()
   * @generated
   * @ordered
   */
  protected static final int STUDENT_COUNT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getStudentCount() <em>Student Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStudentCount()
   * @generated
   * @ordered
   */
  protected int studentCount = STUDENT_COUNT_EDEFAULT;

  /**
   * The default value of the '{@link #getDay() <em>Day</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDay()
   * @generated
   * @ordered
   */
  protected static final Day DAY_EDEFAULT = Day.MON;

  /**
   * The cached value of the '{@link #getDay() <em>Day</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDay()
   * @generated
   * @ordered
   */
  protected Day day = DAY_EDEFAULT;

  /**
   * The cached value of the '{@link #getBatches() <em>Batches</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBatches()
   * @generated
   * @ordered
   */
  protected EList<String> batches;

  /**
   * The cached value of the '{@link #getPrefers() <em>Prefers</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrefers()
   * @generated
   * @ordered
   */
  protected EList<Day> prefers;

  /**
   * The cached value of the '{@link #getPreferredSessions() <em>Preferred Sessions</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPreferredSessions()
   * @generated
   * @ordered
   */
  protected EList<Integer> preferredSessions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CourseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CourseSchedulerPackage.Literals.COURSE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTeacherName()
  {
    return teacherName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTeacherName(String newTeacherName)
  {
    String oldTeacherName = teacherName;
    teacherName = newTeacherName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CourseSchedulerPackage.COURSE__TEACHER_NAME, oldTeacherName, teacherName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTeacherId()
  {
    return teacherId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTeacherId(String newTeacherId)
  {
    String oldTeacherId = teacherId;
    teacherId = newTeacherId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CourseSchedulerPackage.COURSE__TEACHER_ID, oldTeacherId, teacherId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getDuration()
  {
    return duration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDuration(int newDuration)
  {
    int oldDuration = duration;
    duration = newDuration;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CourseSchedulerPackage.COURSE__DURATION, oldDuration, duration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getSessions()
  {
    return sessions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSessions(int newSessions)
  {
    int oldSessions = sessions;
    sessions = newSessions;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CourseSchedulerPackage.COURSE__SESSIONS, oldSessions, sessions));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getStudentCount()
  {
    return studentCount;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStudentCount(int newStudentCount)
  {
    int oldStudentCount = studentCount;
    studentCount = newStudentCount;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CourseSchedulerPackage.COURSE__STUDENT_COUNT, oldStudentCount, studentCount));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Day getDay()
  {
    return day;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDay(Day newDay)
  {
    Day oldDay = day;
    day = newDay == null ? DAY_EDEFAULT : newDay;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CourseSchedulerPackage.COURSE__DAY, oldDay, day));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getBatches()
  {
    if (batches == null)
    {
      batches = new EDataTypeEList<String>(String.class, this, CourseSchedulerPackage.COURSE__BATCHES);
    }
    return batches;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Day> getPrefers()
  {
    if (prefers == null)
    {
      prefers = new EDataTypeEList<Day>(Day.class, this, CourseSchedulerPackage.COURSE__PREFERS);
    }
    return prefers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Integer> getPreferredSessions()
  {
    if (preferredSessions == null)
    {
      preferredSessions = new EDataTypeEList<Integer>(Integer.class, this, CourseSchedulerPackage.COURSE__PREFERRED_SESSIONS);
    }
    return preferredSessions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CourseSchedulerPackage.COURSE__TEACHER_NAME:
        return getTeacherName();
      case CourseSchedulerPackage.COURSE__TEACHER_ID:
        return getTeacherId();
      case CourseSchedulerPackage.COURSE__DURATION:
        return getDuration();
      case CourseSchedulerPackage.COURSE__SESSIONS:
        return getSessions();
      case CourseSchedulerPackage.COURSE__STUDENT_COUNT:
        return getStudentCount();
      case CourseSchedulerPackage.COURSE__DAY:
        return getDay();
      case CourseSchedulerPackage.COURSE__BATCHES:
        return getBatches();
      case CourseSchedulerPackage.COURSE__PREFERS:
        return getPrefers();
      case CourseSchedulerPackage.COURSE__PREFERRED_SESSIONS:
        return getPreferredSessions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CourseSchedulerPackage.COURSE__TEACHER_NAME:
        setTeacherName((String)newValue);
        return;
      case CourseSchedulerPackage.COURSE__TEACHER_ID:
        setTeacherId((String)newValue);
        return;
      case CourseSchedulerPackage.COURSE__DURATION:
        setDuration((Integer)newValue);
        return;
      case CourseSchedulerPackage.COURSE__SESSIONS:
        setSessions((Integer)newValue);
        return;
      case CourseSchedulerPackage.COURSE__STUDENT_COUNT:
        setStudentCount((Integer)newValue);
        return;
      case CourseSchedulerPackage.COURSE__DAY:
        setDay((Day)newValue);
        return;
      case CourseSchedulerPackage.COURSE__BATCHES:
        getBatches().clear();
        getBatches().addAll((Collection<? extends String>)newValue);
        return;
      case CourseSchedulerPackage.COURSE__PREFERS:
        getPrefers().clear();
        getPrefers().addAll((Collection<? extends Day>)newValue);
        return;
      case CourseSchedulerPackage.COURSE__PREFERRED_SESSIONS:
        getPreferredSessions().clear();
        getPreferredSessions().addAll((Collection<? extends Integer>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CourseSchedulerPackage.COURSE__TEACHER_NAME:
        setTeacherName(TEACHER_NAME_EDEFAULT);
        return;
      case CourseSchedulerPackage.COURSE__TEACHER_ID:
        setTeacherId(TEACHER_ID_EDEFAULT);
        return;
      case CourseSchedulerPackage.COURSE__DURATION:
        setDuration(DURATION_EDEFAULT);
        return;
      case CourseSchedulerPackage.COURSE__SESSIONS:
        setSessions(SESSIONS_EDEFAULT);
        return;
      case CourseSchedulerPackage.COURSE__STUDENT_COUNT:
        setStudentCount(STUDENT_COUNT_EDEFAULT);
        return;
      case CourseSchedulerPackage.COURSE__DAY:
        setDay(DAY_EDEFAULT);
        return;
      case CourseSchedulerPackage.COURSE__BATCHES:
        getBatches().clear();
        return;
      case CourseSchedulerPackage.COURSE__PREFERS:
        getPrefers().clear();
        return;
      case CourseSchedulerPackage.COURSE__PREFERRED_SESSIONS:
        getPreferredSessions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CourseSchedulerPackage.COURSE__TEACHER_NAME:
        return TEACHER_NAME_EDEFAULT == null ? teacherName != null : !TEACHER_NAME_EDEFAULT.equals(teacherName);
      case CourseSchedulerPackage.COURSE__TEACHER_ID:
        return TEACHER_ID_EDEFAULT == null ? teacherId != null : !TEACHER_ID_EDEFAULT.equals(teacherId);
      case CourseSchedulerPackage.COURSE__DURATION:
        return duration != DURATION_EDEFAULT;
      case CourseSchedulerPackage.COURSE__SESSIONS:
        return sessions != SESSIONS_EDEFAULT;
      case CourseSchedulerPackage.COURSE__STUDENT_COUNT:
        return studentCount != STUDENT_COUNT_EDEFAULT;
      case CourseSchedulerPackage.COURSE__DAY:
        return day != DAY_EDEFAULT;
      case CourseSchedulerPackage.COURSE__BATCHES:
        return batches != null && !batches.isEmpty();
      case CourseSchedulerPackage.COURSE__PREFERS:
        return prefers != null && !prefers.isEmpty();
      case CourseSchedulerPackage.COURSE__PREFERRED_SESSIONS:
        return preferredSessions != null && !preferredSessions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (teacherName: ");
    result.append(teacherName);
    result.append(", teacherId: ");
    result.append(teacherId);
    result.append(", duration: ");
    result.append(duration);
    result.append(", sessions: ");
    result.append(sessions);
    result.append(", studentCount: ");
    result.append(studentCount);
    result.append(", day: ");
    result.append(day);
    result.append(", batches: ");
    result.append(batches);
    result.append(", prefers: ");
    result.append(prefers);
    result.append(", preferredSessions: ");
    result.append(preferredSessions);
    result.append(')');
    return result.toString();
  }

} //CourseImpl
