/*
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.tests

import com.google.inject.Inject
import org.aditi.course.scheduler.courseScheduler.CourseScheduler
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(CourseSchedulerInjectorProvider)
class CourseSchedulerParsingTest {
	@Inject
	ParseHelper<CourseScheduler> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
