/*
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.ui.tests;

import com.google.inject.Injector;
import course.scheduler.ui.internal.SchedulerActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CourseSchedulerUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SchedulerActivator.getInstance().getInjector("org.aditi.course.scheduler.CourseScheduler");
	}

}
