/*
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCourseSchedulerScopeProvider extends DelegatingScopeProvider {
}
