/*
 * generated by Xtext 2.38.0
 */
package org.aditi.course.scheduler.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCourseSchedulerValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.aditi.course.scheduler.courseScheduler.CourseSchedulerPackage.eINSTANCE);
		return result;
	}
}
